export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';

export const USER_COUNT='USER_COUNT';
export const USER_COUNT_INCREMENT ='USER_COUNT_INCREMENT';
export const USER_COUNT_DECREMENT = 'USER_COUNT_DECREMENT';

